version: 2

workflows:
  version: 2
  build:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/node:10
    environment:
      NODE_ENV: test
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package.json" }}
      - run: yarn snyk-protect
      - run: yarn prepublish
      - run: yarn test